services:
  frontend:
    container_name: frontend
    image: ghcr.io/${REPO_OWNER?REPO_OWNER not set}/frontend:${IMAGE_TAG:-latest}
    ports:
      - "3000:3000"
    environment:
      GRAPHQL_URL: ${GRAPHQL_URL:-http://gateway:8080/graphql/query}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL:-http://auth:8081/query}
    networks:
      - shop_default

networks:
  shop_default:
    external: true
